### ISSUE TITLE
A problem occurred evaluating project ':media_kit_libs_android_video'.

### ISSUE THREAD

**Issue by JieNengi** [abdelaziz-mahdy/flutter_meedu_videoplayer#176]
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/9f72ffd7-78e9-49e0-8c07-04d117651fa1)
try flutter clean, but it is invalid.

**Comment by zezo357** [comment]
Please use latest version of media_kit


Or latest version of fvp


Using a dependancy override

**Comment by KBoss174** [comment]
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/30442394/8cf697b1-dbcf-4439-9f55-1a0108728c20)
I have the same problem

**Comment by zezo357** [comment]
Sadly I can help with that , maybe a pub upgrade will help
