### ISSUE TITLE
on Windows.....error GC9768DF9: Undefined name 'NativeLibrary'.

### ISSUE THREAD

**Issue by JieNengi** [abdelaziz-mahdy/flutter_meedu_videoplayer#177]
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/834312f1-c7d2-4e4a-8d5b-cd99f9cf2fa5)

**Comment by zezo357** [comment]
What version of the package are you using?

**Comment by zezo357** [comment]
Also 99% it's not the latest since it's using media_kit

**Comment by zezo357** [comment]
use media_kit latest version please 
since there have been alot of changes recently to it,
