### ISSUE TITLE
The video jumps back to the beginning to speed up

### ISSUE THREAD

**Issue by xfdyd** [abdelaziz-mahdy/flutter_meedu_videoplayer#179]
APP Pilipala uses this player, under Android 6, within 3 minutes of online video playback, the video often jumps back to the beginning to speed up, while the audio continues to play backwards.

**Comment by zezo357** [comment]
Which version are you using? And are using fvp or not for Android? 

And try with and without it , 


Keep in mind I can't support the package anymore so I recommend moving on to media_kit

**Comment by zezo357** [comment]
For the fvp option you can find it in `initMeeduPlayer()`
