### ISSUE TITLE
Error: 'Durations' is imported from both 'package:flutter/src/material/motion.dart' and 'package:flutter_meedu_videoplayer/src/helpers/durations.dart'.     this.durations = const Durations(),

### ISSUE THREAD

**Issue by JieNengi** [abdelaziz-mahdy/flutter_meedu_videoplayer#182]
![QQ截图20231210121157](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/8c4ce85a-9e88-4e11-8f6e-67516e7faf3c)

try  flutter clean,It still is.

**Comment by zezo357** [comment]
It's a breaking change because of the flutter version, and sorry I can't maintain the package anymore, so you have two options


Migrate to media_kit 


Create a fork and fix the issue and use that fork

**Comment by abdelaziz-mahdy** [comment]
updated deps on main thanks to https://github.com/abdelaziz-mahdy/flutter_meedu_videoplayer/pull/186 i think that fixes your issue
