### ISSUE TITLE
How to load subtitles（SRT）, I couldn't find this method

### ISSUE THREAD

**Issue by JieNengi** [abdelaziz-mahdy/flutter_meedu_videoplayer#183]
I am still using this package😂

**Comment by zezo357** [comment]
I don't remember correctly, but I think there are examples with subtitles

**Comment by zezo357** [comment]
And I recommend migrating to media_kit since I can't provide updates here, and my time is limited sadly 🥺

**Comment by abdelaziz-mahdy** [comment]
https://github.com/abdelaziz-mahdy/flutter_meedu_videoplayer/blob/master/package/example/lib/pages/multi_subtitles.dart the subs example.
