### ISSUE TITLE
Flutter 3.16.9 macOS Unable to play video

### ISSUE THREAD

**Issue by ShareZore** [abdelaziz-mahdy/flutter_meedu_videoplayer#184]
Flutter 3.16.9 macOS Unable to play video

log:

[flutter_meedu_videoplayer] Fit is BoxFit.fill
[flutter_meedu_videoplayer] Last fit used was fitHeight
[flutter_meedu_videoplayer] 'dart:core-patch/finalizer_patch.dart': Failed assertion: line 41 pos 12: '<optimized out>': The token should not be the value being attached
[flutter_meedu_videoplayer] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _FinalizerImpl.attach (dart:core-patch/finalizer_patch.dart:41:12)
#3      new Player (package:fvp/src/player.dart:28:9)
#4      MdkVideoPlayer.create (package:fvp/src/video_player_mdk.dart:123:24)
#5      VideoPlayerController.initialize (package:video_player/video_player.dart:438:46)
#6      MeeduPlayerController.setDataSource (package:flutter_meedu_videoplayer/src/controller.dart:534:37)
#7      _VideoWidgetState.initState.<anonymous closure> (package:pecker/common/widgets/image_prew_widget.dart:352:32)
#8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264:9)
#10     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#11     _invoke (dart:ui/hooks.dart:312:13)
#12     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#13     _drawFrame (dart:ui/hooks.dart:283:31)

[flutter_meedu_videoplayer] Fit is BoxFit.fitHeight
[flutter_meedu_videoplayer] Fit is BoxFit.fitHeight

**Comment by zezo357** [comment]
Check with 
https://pub.dev/packages/fvp/changelog
Since the error most probably on their side

**Comment by zezo357** [comment]
Note: from fvp change log there was an error which was fixed on version 0.11.0 so try a flutter upgrade, maybe that will fix it

**Comment by ShareZore** [comment]
> 注意：从 fvp 更改日志来看，有一个错误已在版本 0.11.0 上修复，因此请尝试 flutter 升级，也许这会修复它

ok

**Comment by abdelaziz-mahdy** [comment]
updated deps on main thanks to https://github.com/abdelaziz-mahdy/flutter_meedu_videoplayer/pull/186 i think that fixes your issue
