### ISSUE TITLE
How to fix this failure to play in windwos

### ISSUE THREAD

**Issue by JieNengi** [abdelaziz-mahdy/flutter_meedu_videoplayer#185]
initMeeduPlayer();

[flutter_meedu_videoplayer] 'dart:core-patch/finalizer_patch.dart': Failed assertion: line 41 pos 12: '<optimized out>': The token should not be the value being attached
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/f0776d9e-d4ca-409d-8648-f8a60ffa1762)

![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/6cea1f0a-8441-45cf-b4cf-fe85c38420c7)

**Comment by vaaniiaa** [comment]
@abdelaziz-mahdy I faced same problem and error , I updated fvp package and video_player package but it did not work and still this error exists.
let me know if there is any other solution. 
thank you

**Comment by abdelaziz-mahdy** [comment]
> @abdelaziz-mahdy I faced same problem and error on android , I updated fvp package and video_player package but it did not work and still this error exists.
> let me know if there is any other solution. 
> thank you

Open an issue on fvp repo, since the error logs state that's the error came from fvp and they may know how to solve it

**Comment by JieNengi** [comment]
> @JieNengi did you solve this error?

Pull package, fvp modified to fvp: ^0.14.0
Finally, introduce in your project
  flutter_meedu_videoplayer.
    path: /flutter_meedu_videoplayer/package

**Comment by abdelaziz-mahdy** [comment]
Btw no need to use path for my package a flutter upgrade is enough.

**Comment by abdelaziz-mahdy** [comment]
updated deps on main thanks to https://github.com/abdelaziz-mahdy/flutter_meedu_videoplayer/pull/186 i think that fixes your issue

**Comment by abdelaziz-mahdy** [comment]
if you are still using the package, i upgraded the pub version too
